version: '3.8'
    
services:
  app:
    image: node1/app:1.0
    build: ./app
    container_name: 'node1_app'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    working_dir: '/var/www/html'
    volumes:
      - ../app:/var/www/html
    depends_on:
      - db

  db:
    image: mongo:4.4-bionic
    container_name: 'node1_db'
    expose: 
      - "27017"
    environment:
      - TZ=Asia/Tokyo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=mongo
    volumes:
      - ../db/database:/data/db
      - ../db/init:/docker-entrypoint-initdb.d
